[versions]
    kotlin = "2.2.20"
    jdk = "21"
    kotlinx-serialization = "1.9.0"
    kotlinx-coroutines = "1.10.2"
    ktor = "3.3.1"
    bouncycastle = "1.83"
    exposed = "0.61.0"
    exposed-migration = "1.0.0-rc-3"
    hikaricp = "7.0.2"
    postgresql = "42.7.8"
    dotenv = "6.5.1"
    hoplite = "2.9.0"
    logback = "1.5.19"
    kotlin-logging = "7.0.13"
    klogging = "0.11.6"
    jansi = "2.4.2"
    janino = "3.1.12"
    logstash-logback-encoder = "9.0"
    tgbotapi = "30.0.2"
    protobuf-kotlin = "4.33.2"
    grpc-stub = "1.77.0"
    grpc-kotlin-stub = "1.5.0"
    protobuf = "0.9.5"
    protoc = "4.33.2"
    sshd = "3.0.0-M2"

[libraries]
    kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }

    bouncycastle-bcprov = { module = "org.bouncycastle:bcprov-jdk18on", version.ref = "bouncycastle"}
    bouncycastle-bcpkix = { module = "org.bouncycastle:bcpkix-jdk18on", version.ref = "bouncycastle"}
    bouncycastle-bcutil = { module = "org.bouncycastle:bcutil-jdk18on", version.ref = "bouncycastle"}

    kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
    kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }

    ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
    ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }

    ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
    ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }

    ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
    ktor-server = { module = "io.ktor:ktor-server", version.ref = "ktor" }
    ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
    ktor-server-cio = { module = "io.ktor:ktor-server-cio", version.ref = "ktor" }

    protobuf-kotlin = { module = "com.google.protobuf:protobuf-kotlin", version.ref = "protobuf-kotlin"}
    grpc-protobuf = { module = "io.grpc:grpc-protobuf", version.ref = "grpc-stub"}
    grpc-stub = { module = "io.grpc:grpc-stub", version.ref = "grpc-stub"}
    grpc-kotlin-stub = { module = "io.grpc:grpc-kotlin-stub", version.ref = "grpc-kotlin-stub"}
    protobuf-protoc = { module = "com.google.protobuf:protoc", version.ref = "protoc"}
    protoc-gen-grpc-java = { module = "io.grpc:protoc-gen-grpc-java", version.ref = "grpc-stub"}
    protoc-gen-grpc-kotlin = { module = "io.grpc:protoc-gen-grpc-kotlin", version.ref = "grpc-kotlin-stub"}
    grpc-netty-shaded = { module = "io.grpc:grpc-netty-shaded", version.ref = "grpc-stub" }

    exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed" }
    exposed-crypt = { module = "org.jetbrains.exposed:exposed-crypt", version.ref = "exposed" }
    exposed-dao = { module = "org.jetbrains.exposed:exposed-dao", version.ref = "exposed" }
    exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed" }

    hikaricp = { module = "com.zaxxer:HikariCP", version.ref = "hikaricp" }

    exposed-jodatime = { module = "org.jetbrains.exposed:exposed-jodatime", version.ref = "exposed" }
    exposed-java-time = { module = "org.jetbrains.exposed:exposed-java-time", version.ref = "exposed" }
    exposed-kotlin-datetime = { module = "org.jetbrains.exposed:exposed-kotlin-datetime", version.ref = "exposed" }
    exposed-json = { module = "org.jetbrains.exposed:exposed-json", version.ref = "exposed" }
    exposed-money = { module = "org.jetbrains.exposed:exposed-money", version.ref = "exposed" }

    exposed-migration-core = { module = "org.jetbrains.exposed:exposed-migration-core", version.ref = "exposed-migration" }
    exposed-migration-jdbc = { module = "org.jetbrains.exposed:exposed-migration-jdbc", version.ref = "exposed-migration" }

    postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }

    dotenv-kotlin = {module = "io.github.cdimascio:dotenv-kotlin", version.ref = "dotenv" }
    hoplite-core = { module = "com.sksamuel.hoplite:hoplite-core", version.ref = "hoplite" }
    hoplite-toml = { module = "com.sksamuel.hoplite:hoplite-toml", version.ref = "hoplite" }
    hoplite-yaml = { module = "com.sksamuel.hoplite:hoplite-yaml", version.ref = "hoplite" }
    hoplite-json = { module = "com.sksamuel.hoplite:hoplite-json", version.ref = "hoplite" }
    hoplite-hocon = { module = "com.sksamuel.hoplite:hoplite-hocon", version.ref = "hoplite" }

    logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
    kotlin-logging = { module = "io.github.oshai:kotlin-logging", version.ref = "kotlin-logging" }
    klogging = { module = "io.klogging:klogging", version.ref = "klogging" }
    logstash-logback-encoder = { module = "net.logstash.logback:logstash-logback-encoder", version.ref = "logstash-logback-encoder" }

    jansi = { module = "org.fusesource.jansi:jansi", version.ref = "jansi" }
    janino = { module = "org.codehaus.janino:janino", version.ref = "janino" }

    tgbotapi = { module = "dev.inmo:tgbotapi", version.ref = "tgbotapi" }

    sshd-core = { module = "org.apache.sshd:sshd-core", version.ref = "sshd" }
    sshd-sftp = { module = "org.apache.sshd:sshd-sftp", version.ref = "sshd" }


    #sample = { module = "", version.ref = "" }
    #sample = { module = "", version.ref = "" }
    #sample = { module = "", version.ref = "" }
    #sample = { module = "", version.ref = "" }
    #sample = { module = "", version.ref = "" }
    #sample = { module = "", version.ref = "" }
    #sample = { module = "", version.ref = "" }
    #sample = { module = "", version.ref = "" }
    #sample = { module = "", version.ref = "" }
    #sample = { module = "", version.ref = "" }

[plugins]
    kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
    kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
    protobuf = { id = "com.google.protobuf", version.ref = "protobuf" }
