logging:
  logDir: "devLogs"
  rootLevel: TRACE
  maxFileSize: 50MB
  maxHistory: 5
  totalSizeCap: 1GB
  consoleAppender:
    enabled: true
    threshold: TRACE
  fileAppender:
    enabled: false
    threshold: INFO
  jsonAppender:
    enabled: false
    threshold: INFO
