logging:
  logDir: "prodLogs"
  rootLevel: INFO
  maxFileSize: 100MB
  maxHistory: 14
  totalSizeCap: 5GB
  consoleAppender:
    enabled: true
    threshold: INFO
  fileAppender:
    enabled: true
    threshold: INFO
  jsonAppender:
    enabled: true
    threshold: INFO
